# Generated by Django 3.0.8 on 2020-09-29 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0003_user_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_data',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='schedule',
            name='installer_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installer_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
