# Generated by Django 3.0.8 on 2020-09-29 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0004_auto_20200929_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='installer_appointment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='installer_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_appointment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
