# Generated by Django 3.0.8 on 2020-09-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0006_auto_20200929_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_data', models.CharField(max_length=140)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_day', to=settings.AUTH_USER_MODEL)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installer_day', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_data', to='installers.Day'),
        ),
    ]
